spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/gekitsui?sslmode=require}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  rabbitmq:
    addresses: ${CLOUDAMQP_URL:amqp://guest:guest@localhost}
