spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: PUT_YOUR_CLIENT_ID
            client-secret: PUT_YOUR_CLIENT_SECRET
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/gekitsui?sslmode=require}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  rabbitmq:
    addresses: ${CLOUDAMQP_URL:amqp://guest:guest@localhost}
  cache:
    jcache:
      config: classpath:ehcache.xml
  mvc:
    static-path-pattern: /static/**
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-order: 10
      url: /api/.*
      rate-limits:
        - expression: "@securityService.userid()"
          bandwidths:
          - capacity: 30
            time: 1
            unit: hours
gekitsui:
  admins: blue-jam
  cookie:
    user-salt: salt
  submission:
    max-testcase-size: 2000
